const GovMunicip = {
  tunis: [
    'tunis',
    'bardo',
    'kram',
    'goulette',
    'carthage',
    'sidi bou said',
    'marsa',
    'sidi hassine',
  ],
  ariana: [
    'ariana',
    'soukra',
    'raoued',
    'kalâat el-andalous',
    'sidi thabet',
    'ettadhamen-mnihla',
  ],
  'ben arous': [
    'ben arous',
    'el mourouj',
    'hammam lif',
    'hammam chott',
    'bou mhel el-bassatine',
    'ezzahra',
    'radès',
    'mégrine',
    'mohamedia-fouchana',
    'mornag',
    'khalidia',
  ],
  mannouba: [
    'mannouba',
    'den den',
    'douar hicher',
    'oued ellil',
    'mornaguia',
    'borj el amri',
    'djedeida',
    'tebourba',
    'el' + ' battan',
  ],
};

export default GovMunicip;
