name: Lint and format www

on:
  push:
    branches:
      - main
    paths:
      - 'www/src/**'
  pull_request:
    types: [opened]
    branches:
      - main
    paths:
      - 'www/src/**'

jobs:
  lint-and-format:
    name: linting and prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js Environment
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run linter & formatter
        uses: wearerequired/lint-action@v1.10.0
        with:
          eslint: true
          eslint_extensions: ts
          prettier: true
