name: Lint and format

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]
    branches:
      - main

jobs:
  lint-and-format:
    name: linting and prettier
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run linter & formatter
        uses: wearerequired/lint-action@v1.10.0
        with:
          commit_message: 'style: lint code with ${linter}'
          auto_fix: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          eslint: true
          eslint_extensions: ts
          prettier: true
