name: www production Build && Deploy to S3

on:
  push:
    branches:
      - main
    paths:
      - 'www/**'
  pull_request:
    types: [opened]
    branches:
      - main
    paths:
      - 'www/**'


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./www
    steps:
      - uses: actions/checkout@v2
      - name: Nodejs environment setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          cd .. && npm install
          cd www && npm install
      - name: Production Build
        run: |
          npm run build
#      - name: e2e Tests
#        run: |
#          npm run test:e2e
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./build s3://${{ secrets.AWS_PRODUCTION_BUCKET_NAME }}
